### ISSUE TITLE
Fatal Error for Anonymous User

### ISSUE THREAD

**Issue by sleewok** [mr-vara/me.vara.civialerts#3]
With this extension anonymous users get a fatal error when trying to access an event registration page. Here is the error:

`
CiviCRM_API3_Exception: "A fatal error was triggered: is not of type Text"

#0 /var/aegir/platforms/civicrm4/CustomExtensions/me.vara.civialerts/civialerts.php(26): civicrm_api3("CiviAlerts", "get", (Array:2))
#1 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Utils/Hook.php(282): civialerts_civicrm_alterContent("<!-- .tpl file invoked: CRM/Event/Form/Registration/Register.tpl. Call via fo...", "form", "CRM/Event/Form/Registration/Register.tpl", Object(CRM_Event_Form_Registration_Register))
#2 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(84): CRM_Utils_Hook->runHooks((Array:88), "civicrm_alterContent", 4, "<!-- .tpl file invoked: CRM/Event/Form/Registration/Register.tpl. Call via fo...", "form", "CRM/Event/Form/Registration/Register.tpl", Object(CRM_Event_Form_Registration_Register), NULL, NULL)
#3 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(98): CRM_Utils_Hook_DrupalBase->invokeViaUF(4, "<!-- .tpl file invoked: CRM/Event/Form/Registration/Register.tpl. Call via fo...", "form", "CRM/Event/Form/Registration/Register.tpl", Object(CRM_Event_Form_Registration_Register), NULL, NULL, "civicrm_alterContent")
#4 [internal function](): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_alterContent", Object(Civi\Core\CiviEventDispatcher))
#5 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func((Array:2), Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_alterContent", Object(Civi\Core\CiviEventDispatcher))
#6 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:1), "hook_civicrm_alterContent", Object(Civi\Core\Event\GenericHookEvent))
#7 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("hook_civicrm_alterContent", Object(Civi\Core\Event\GenericHookEvent))
#8 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch("hook_civicrm_alterContent", Object(Civi\Core\Event\GenericHookEvent))
#9 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Utils/Hook.php(164): Civi\Core\CiviEventDispatcher->dispatch("hook_civicrm_alterContent", Object(Civi\Core\Event\GenericHookEvent))
#10 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Utils/Hook.php(1520): CRM_Utils_Hook->invoke((Array:4), "<!-- .tpl file invoked: CRM/Event/Form/Registration/Register.tpl. Call via fo...", "form", "CRM/Event/Form/Registration/Register.tpl", Object(CRM_Event_Form_Registration_Register), NULL, NULL, "civicrm_alterContent")
#11 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php(144): CRM_Utils_Hook::alterContent("<!-- .tpl file invoked: CRM/Event/Form/Registration/Register.tpl. Call via fo...", "form", "CRM/Event/Form/Registration/Register.tpl", Object(CRM_Event_Form_Registration_Register))
#12 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php(99): CRM_Core_QuickForm_Action_Display->renderForm(Object(CRM_Event_Form_Registration_Register))
#13 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Event_Form_Registration_Register), "display")
#14 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Event_Form_Registration_Register), "display")
#15 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("display")
#16 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Core_Controller->run((Array:3), NULL)
#17 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#18 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#19 /var/aegir/platforms/civicrm4/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#20 /var/aegir/platforms/civicrm4/includes/menu.inc(527): civicrm_invoke("event", "register")
#21 /var/aegir/platforms/civicrm4/index.php(21): menu_execute_active_handler()
#22 {main}
`

**Comment by sleewok** [comment]
Line 26 of civialerts.php is causing the error.

**Comment by sleewok** [comment]
Nevermind. Our local version of the extension was not updated to your most recent changes.
